# Test your FastAPI endpoints

POST http://127.0.0.1:8000/process-file-paths/
Content-Type: application/json

{
  "filePaths": [
    "files/image.jpg",
    "files/document.docx",
    "files/textfile.txt",
    "files/pdf-document.pdf"
  ]
}

###